version: '2'

services:
  django_site_nginx:
    image: emarcs/nginx-uwsgi
    ports:
      - 8081:80
    links:
      - django_site_uwsgi:uwsgi_srv
  django_site_uwsgi:
    image: emarcs/django:py2
    volumes:
      - ./data:/srv/django/app
