version: '3'

services:
  gate:
    container_name: django-test-gate
    image: emarcs/nginx-uwsgi
    ports:
      - 8081:80
    links:
      - app:uwsgi_srv
  app:
    container_name: django-test-app
    image: emarcs/django
    environment:
      DJANGO_PROJECT_NAME: data
      DJANGO_SETTINGS_MODULE: data.settings
    volumes:
      - ./data:/srv/django/app
